version: '3'

services:
  web:
    volumes:
      - ./docker/dev/web/nginx.conf:/etc/nginx/nginx.conf

  php:
    build:
      dockerfile: docker/dev/php/Dockerfile
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_USERNAME=${CURRENT_USERNAME}
    user: ${CURRENT_UID}:${CURRENT_GID}
    environment:
      - CURRENT_USERNAME=${CURRENT_USERNAME}