api_users_list:
      path: /api/users
      defaults: { _controller: AppBundle:User:index }
      methods: [GET]

api_users_create:
      path: /api/users
      defaults: { _controller: AppBundle:User:create, _format: json }
      methods: [POST]

api_users_edit:
      path: /api/users/{id}
      defaults: { _controller: AppBundle:User:edit, _format: json }
      methods: [PUT]
      requirements:
          id: '\d+'

api_users_delete:
      path: /api/users/{id}
      defaults: { _controller: AppBundle:User:delete }
      methods: [DELETE]
      requirements:
          id: '\d+'

api_groups_list:
      path: /api/groups
      defaults: { _controller: AppBundle:UserGroup:index }
      methods: [GET]

api_groups_show:
      path: /api/groups/{id}
      defaults: { _controller: AppBundle:UserGroup:show }
      methods: [GET]

api_group_create:
      path: /api/groups
      defaults: { _controller: AppBundle:UserGroup:create, _format: json }
      methods: [POST]
      requirements:
          id: '\d+'

api_group_edit:
      path: /api/groups/{id}
      defaults: { _controller: AppBundle:UserGroup:edit, _format: json }
      methods: [PUT]
      requirements:
          id: '\d+'

api_group_delete:
      path: /api/groups/{id}
      defaults: { _controller: AppBundle:UserGroup:delete }
      methods: [DELETE]
      requirements:
          id: '\d+'

api_add_user_to_group:
      path: /api/groups/{id}/add
      defaults: { _controller: AppBundle:UserGroup:userAdd, _format: json  }
      methods: [PUT]
      requirements:
          id: '\d+'

api_del_user_from_group:
      path: /api/groups/{id}/del
      defaults: { _controller: AppBundle:UserGroup:userDel, _format: json  }
      methods: [DELETE]
      requirements:
          id: '\d+'

root:
      path: /
      defaults:
          _controller: FrameworkBundle:Redirect:urlRedirect
          path: /api/users
          methods: [GET]