api_users_list:
      path: /api/users
      defaults: { _controller: AppBundle:User:index }
      methods: [GET]

api_users_create:
      path: /api/users
      defaults: { _controller: AppBundle:User:create}
      methods: [POST]

api_users_edit:
      path: /api/users/{id}
      defaults: { _controller: AppBundle:User:edit, _format: json}
      methods: [PUT]
      requirements:
          id: '\d+'

api_users_delete:
      path: /api/users/{id}
      defaults: { _controller: AppBundle:User:delete}
      methods: [DELETE]
      requirements:
          id: '\d+'
