api_users_list:
      path: /api/users
      defaults: { _controller: AppBundle:Users\User:index }
      methods: [GET]

api_users_show:
      path: /api/users/{id}
      defaults: { _controller: AppBundle:Users\User:show }
      methods: [GET]
      requirements:
          id: '\d+'