services:
    app.user_service:
        class: AppBundle\Services\UserService
        public: true
        autowire: true

    api_exception_subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    doctrine.orm.validator.unique:
        class: Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator
        autowire: true
        public: true
        tags:
            - { name: validator.constraint_validator }
